# Site
name: "Muhammad Usman"
title: "CodeNinjaUsman"
description: "Personal Website."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'G-0QLKDLG322'
disqus: 'codeninjausman-1'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Muhammad Usman
    display_name: CodeNinjaUsman
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: bytesofusman@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/CodeNinjaUsman
    description: "I am Usman a teen programmer and cyber expert."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
